// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pod.proto

/*
Package pod is a generated protocol buffer package.

Package pod defines data model for Kubernetes Pod.

It is generated from these files:
	pod.proto

It has these top-level messages:
	Pod
*/
package pod

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Protocol defines network protocols supported for container ports.
type Pod_Container_Port_Protocol int32

const (
	Pod_Container_Port_TCP Pod_Container_Port_Protocol = 0
	Pod_Container_Port_UDP Pod_Container_Port_Protocol = 1
)

var Pod_Container_Port_Protocol_name = map[int32]string{
	0: "TCP",
	1: "UDP",
}
var Pod_Container_Port_Protocol_value = map[string]int32{
	"TCP": 0,
	"UDP": 1,
}

func (x Pod_Container_Port_Protocol) String() string {
	return proto.EnumName(Pod_Container_Port_Protocol_name, int32(x))
}
func (Pod_Container_Port_Protocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 1, 0, 0}
}

// Pod is a collection of containers that can run on a host.
// This resource is created by clients and scheduled onto hosts.
type Pod struct {
	// Name of the pod unique within the namespace.
	// Cannot be updated.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Namespace the pod is inserted into.
	// An empty namespace is equivalent to the "default" namespace, but "default"
	// is the canonical representation.
	// Cannot be updated.
	Namespace string `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	// A list of labels attached to this pod.
	// +optional
	Label []*Pod_Label `protobuf:"bytes,3,rep,name=label" json:"label,omitempty"`
	// IP address allocated to the pod. Routable at least within the cluster.
	// Empty if not yet allocated.
	// +optional
	IpAddress string `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress" json:"ip_address,omitempty"`
	// IP address of the host to which the pod is assigned.
	// Empty if not yet scheduled.
	// +optional
	HostIpAddress string `protobuf:"bytes,5,opt,name=host_ip_address,json=hostIpAddress" json:"host_ip_address,omitempty"`
	// List of containers belonging to the pod.
	// Containers cannot currently be added or removed.
	// There must be at least one container in a Pod.
	// Cannot be updated.
	Container []*Pod_Container `protobuf:"bytes,6,rep,name=container" json:"container,omitempty"`
	// Network namespace used by the pod
	NetworkNamespace string `protobuf:"bytes,7,opt,name=network_namespace,json=networkNamespace" json:"network_namespace,omitempty"`
	// Container ID of pod's sandbox
	PodSanbox string `protobuf:"bytes,8,opt,name=pod_sanbox,json=podSanbox" json:"pod_sanbox,omitempty"`
}

func (m *Pod) Reset()                    { *m = Pod{} }
func (m *Pod) String() string            { return proto.CompactTextString(m) }
func (*Pod) ProtoMessage()               {}
func (*Pod) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Pod) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pod) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Pod) GetLabel() []*Pod_Label {
	if m != nil {
		return m.Label
	}
	return nil
}

func (m *Pod) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *Pod) GetHostIpAddress() string {
	if m != nil {
		return m.HostIpAddress
	}
	return ""
}

func (m *Pod) GetContainer() []*Pod_Container {
	if m != nil {
		return m.Container
	}
	return nil
}

func (m *Pod) GetNetworkNamespace() string {
	if m != nil {
		return m.NetworkNamespace
	}
	return ""
}

func (m *Pod) GetPodSanbox() string {
	if m != nil {
		return m.PodSanbox
	}
	return ""
}

// Label is a key/value pair attached to an object (pod in this case).
// Labels are used to organize and to select subsets of objects.
type Pod_Label struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Pod_Label) Reset()                    { *m = Pod_Label{} }
func (m *Pod_Label) String() string            { return proto.CompactTextString(m) }
func (*Pod_Label) ProtoMessage()               {}
func (*Pod_Label) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Pod_Label) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Pod_Label) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// A single application container run within a pod.
type Pod_Container struct {
	// Name of the container.
	// Each container in a pod has a unique name.
	// Cannot be updated.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// List of ports to expose from the container. Exposing a port here gives
	// the system additional information about the network connections a
	// container uses, but it is primarily informational. Not specifying a port
	// here DOES NOT prevent that port from being exposed. Any port which is
	// listening on the default "0.0.0.0" address inside a container will be
	// accessible from the network.
	// Cannot be updated.
	// +optional
	Port []*Pod_Container_Port `protobuf:"bytes,2,rep,name=port" json:"port,omitempty"`
}

func (m *Pod_Container) Reset()                    { *m = Pod_Container{} }
func (m *Pod_Container) String() string            { return proto.CompactTextString(m) }
func (*Pod_Container) ProtoMessage()               {}
func (*Pod_Container) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *Pod_Container) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pod_Container) GetPort() []*Pod_Container_Port {
	if m != nil {
		return m.Port
	}
	return nil
}

// Port represents a network port in a single container.
type Pod_Container_Port struct {
	// An IANA_SVC_NAME formatted port name, unique within the pod.
	// The name can be referred to by services, policies, ...
	// +optional
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Port number to expose on the host.
	// The port number is in the range: 0 < x < 65536.
	// If pod is in the host network namespace, this must match container_port.
	// Most containers do not need this.
	// +optional
	HostPort int32 `protobuf:"varint,2,opt,name=host_port,json=hostPort" json:"host_port,omitempty"`
	// Port number to expose on the pod's IP address.
	// The port number is in the range: 0 < x < 65536.
	ContainerPort int32 `protobuf:"varint,3,opt,name=container_port,json=containerPort" json:"container_port,omitempty"`
	// Protocol for port. Must be UDP or TCP.
	// Defaults to "TCP".
	// +optional
	Protocol Pod_Container_Port_Protocol `protobuf:"varint,4,opt,name=protocol,enum=pod.Pod_Container_Port_Protocol" json:"protocol,omitempty"`
	// What host IP to bind the external port to.
	// +optional
	HostIpAddress string `protobuf:"bytes,5,opt,name=host_ip_address,json=hostIpAddress" json:"host_ip_address,omitempty"`
}

func (m *Pod_Container_Port) Reset()                    { *m = Pod_Container_Port{} }
func (m *Pod_Container_Port) String() string            { return proto.CompactTextString(m) }
func (*Pod_Container_Port) ProtoMessage()               {}
func (*Pod_Container_Port) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1, 0} }

func (m *Pod_Container_Port) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pod_Container_Port) GetHostPort() int32 {
	if m != nil {
		return m.HostPort
	}
	return 0
}

func (m *Pod_Container_Port) GetContainerPort() int32 {
	if m != nil {
		return m.ContainerPort
	}
	return 0
}

func (m *Pod_Container_Port) GetProtocol() Pod_Container_Port_Protocol {
	if m != nil {
		return m.Protocol
	}
	return Pod_Container_Port_TCP
}

func (m *Pod_Container_Port) GetHostIpAddress() string {
	if m != nil {
		return m.HostIpAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*Pod)(nil), "pod.Pod")
	proto.RegisterType((*Pod_Label)(nil), "pod.Pod.Label")
	proto.RegisterType((*Pod_Container)(nil), "pod.Pod.Container")
	proto.RegisterType((*Pod_Container_Port)(nil), "pod.Pod.Container.Port")
	proto.RegisterEnum("pod.Pod_Container_Port_Protocol", Pod_Container_Port_Protocol_name, Pod_Container_Port_Protocol_value)
}

func init() { proto.RegisterFile("pod.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x5d, 0x4b, 0xeb, 0x40,
	0x10, 0xbd, 0x69, 0x92, 0x36, 0x99, 0x4b, 0x7b, 0x73, 0x97, 0x0b, 0x37, 0xd4, 0x16, 0x4a, 0x51,
	0x29, 0x14, 0xa2, 0xd4, 0x57, 0x5f, 0xa4, 0xbe, 0x08, 0x22, 0x21, 0xea, 0x73, 0xd8, 0x76, 0x17,
	0x2c, 0x8d, 0x99, 0x25, 0x89, 0x5f, 0xbf, 0xc0, 0xdf, 0xe3, 0x5f, 0xf2, 0x97, 0xc8, 0x4e, 0xd2,
	0xad, 0x60, 0x05, 0x9f, 0x32, 0x7b, 0xe6, 0xcc, 0xd9, 0x39, 0x67, 0x03, 0xbe, 0x42, 0x11, 0xa9,
	0x02, 0x2b, 0x64, 0xb6, 0x42, 0x31, 0x7e, 0x75, 0xc1, 0x8e, 0x51, 0x30, 0x06, 0x4e, 0xce, 0xef,
	0x65, 0x68, 0x8d, 0xac, 0x89, 0x9f, 0x50, 0xcd, 0x06, 0xe0, 0xeb, 0x6f, 0xa9, 0xf8, 0x52, 0x86,
	0x2d, 0x6a, 0x6c, 0x01, 0xb6, 0x0f, 0x6e, 0xc6, 0x17, 0x32, 0x0b, 0xed, 0x91, 0x3d, 0xf9, 0x3d,
	0xeb, 0x45, 0x5a, 0x39, 0x46, 0x11, 0x5d, 0x6a, 0x34, 0xa9, 0x9b, 0x6c, 0x08, 0xb0, 0x52, 0x29,
	0x17, 0xa2, 0x90, 0x65, 0x19, 0x3a, 0xb5, 0xc8, 0x4a, 0x9d, 0xd5, 0x00, 0x3b, 0x84, 0x3f, 0x77,
	0x58, 0x56, 0xe9, 0x27, 0x8e, 0x4b, 0x9c, 0xae, 0x86, 0x2f, 0x0c, 0xef, 0x18, 0xfc, 0x25, 0xe6,
	0x15, 0x5f, 0xe5, 0xb2, 0x08, 0xdb, 0x74, 0x21, 0x33, 0x17, 0xce, 0x37, 0x9d, 0x64, 0x4b, 0x62,
	0x53, 0xf8, 0x9b, 0xcb, 0xea, 0x09, 0x8b, 0x75, 0xba, 0x35, 0xd1, 0x21, 0xed, 0xa0, 0x69, 0x5c,
	0x19, 0x2f, 0x43, 0x00, 0x85, 0x22, 0x2d, 0x79, 0xbe, 0xc0, 0xe7, 0xd0, 0xab, 0xb7, 0x54, 0x28,
	0xae, 0x09, 0xe8, 0x1f, 0x81, 0x4b, 0xa6, 0x58, 0x00, 0xf6, 0x5a, 0xbe, 0x34, 0x21, 0xe9, 0x92,
	0xfd, 0x03, 0xf7, 0x91, 0x67, 0x0f, 0x9b, 0x7c, 0xea, 0x43, 0xff, 0xad, 0x05, 0xbe, 0xd9, 0x6a,
	0x67, 0xb6, 0x53, 0x70, 0x14, 0x16, 0x55, 0xd8, 0x22, 0x2f, 0xff, 0xbf, 0x7a, 0x89, 0x62, 0x2c,
	0xaa, 0x84, 0x48, 0xfd, 0x77, 0x0b, 0x1c, 0x7d, 0xdc, 0xa9, 0xb4, 0x07, 0x3e, 0x45, 0xd8, 0xc8,
	0x59, 0x13, 0x37, 0xf1, 0x34, 0x40, 0x03, 0x07, 0xd0, 0x33, 0x91, 0xd4, 0x0c, 0x9b, 0x18, 0x5d,
	0x83, 0x12, 0xed, 0x14, 0x3c, 0xfa, 0x27, 0x96, 0x98, 0xd1, 0x1b, 0xf5, 0x66, 0xa3, 0x6f, 0x36,
	0x8a, 0xe2, 0x86, 0x97, 0x98, 0x89, 0x9f, 0x3e, 0xe2, 0x78, 0x00, 0xde, 0x66, 0x9a, 0x75, 0xc0,
	0xbe, 0x99, 0xc7, 0xc1, 0x2f, 0x5d, 0xdc, 0x9e, 0xc7, 0x81, 0xb5, 0x68, 0x93, 0xde, 0xc9, 0x47,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x54, 0xfc, 0xd0, 0xa2, 0x02, 0x00, 0x00,
}
